name: prune-workflows
on:
  workflow_dispatch:
  schedule:
    # Run monthly, at 00:00 on the 1st day of month.
    - cron: '0 0 1 * *'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6