on:
  release:
    types: [created]

  push:
    branches:
      - master

    tags:
      - 'v*'
      - 'rc-*'
      - 'dev-*'
      - 'test-*'

name: Release ssg-go
jobs:
  generate:
    name: Build ssg-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for build
        uses: actions/checkout@master
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ssg-go from flake
        run: |
          nix build .#default

      - name: Zip ssg-go binaries
        run: |
          zip -r ssg-go-x86_64_linux.zip result/bin

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ssg-go-zip
          path: ./ssg-go-x86_64_linux.zip

  release-tag:
    if: ${{ github.ref_type  == 'tag' }}
    name: Release from tag
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: Checkout for release
        uses: actions/checkout@master

      - name: Download pre-built zip artifact
        uses: actions/download-artifact@v4
        with:
          name: ssg-go-zip
          path: ./
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ssg-go-x86_64_linux.zip
          asset_name: ssg-go-x86_64_linux.zip
          asset_content_type: application/zip

  release-branch:
    if: ${{ github.ref_type  == 'branch' }}
    name: Release from branch
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for release
        uses: actions/checkout@master

      - name: Download pre-built zip artifact
        uses: actions/download-artifact@v4
        with:
          name: ssg-go-zip
          path: ./
      
      - name: Get today's date
        run: |
          # Store 2025-01-01 in env $RELEASE_DATE
          echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release for branch ${{ github.ref_name }}
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-${{ env.RELEASE_DATE }}-${{ github.sha }}
          release_name: Release ${{ github.ref_name }} ${{ env.RELEASE_DATE }} ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ssg-go-x86_64_linux.zip
          asset_name: ssg-go-x86_64_linux.zip
          asset_content_type: application/zip
